// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwCZiRH0KNk3vOiCDV4Kb2GYl-abqSyx8',
    appId: '1:976972312564:web:de62d62d2e8f0426b953a1',
    messagingSenderId: '976972312564',
    projectId: 'paysensenew',
    authDomain: 'paysensenew.firebaseapp.com',
    storageBucket: 'paysensenew.appspot.com',
    measurementId: 'G-RWJDZFD61H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDimjijAiJvx5FKAlC7EO6_kSxIYLPfcxw',
    appId: '1:976972312564:android:648fe0b99c565d2bb953a1',
    messagingSenderId: '976972312564',
    projectId: 'paysensenew',
    storageBucket: 'paysensenew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwTDIppMQzKRvb8mZ07iAD207uFvQ89cg',
    appId: '1:976972312564:ios:25d88024541afa45b953a1',
    messagingSenderId: '976972312564',
    projectId: 'paysensenew',
    storageBucket: 'paysensenew.appspot.com',
    iosBundleId: 'com.example.paysense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwTDIppMQzKRvb8mZ07iAD207uFvQ89cg',
    appId: '1:976972312564:ios:25d88024541afa45b953a1',
    messagingSenderId: '976972312564',
    projectId: 'paysensenew',
    storageBucket: 'paysensenew.appspot.com',
    iosBundleId: 'com.example.paysense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwCZiRH0KNk3vOiCDV4Kb2GYl-abqSyx8',
    appId: '1:976972312564:web:21efb2ccdf1ed068b953a1',
    messagingSenderId: '976972312564',
    projectId: 'paysensenew',
    authDomain: 'paysensenew.firebaseapp.com',
    storageBucket: 'paysensenew.appspot.com',
    measurementId: 'G-0TDHXMBNRJ',
  );
}
