// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZXZfBvx3e6HQ4Ffi-RY1NUe3QpVNjx6A',
    appId: '1:120954544713:web:7210420549d9a87ab5d598',
    messagingSenderId: '120954544713',
    projectId: 'newpaysense-83ef4',
    authDomain: 'newpaysense-83ef4.firebaseapp.com',
    storageBucket: 'newpaysense-83ef4.appspot.com',
    measurementId: 'G-RBBHGTT1FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3llaWkO39ArzsHTlTWgN0HS--IIZJ-tY',
    appId: '1:120954544713:android:18f4c28b564c38e0b5d598',
    messagingSenderId: '120954544713',
    projectId: 'newpaysense-83ef4',
    storageBucket: 'newpaysense-83ef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXCLCW2cYqJY975bxP10PZ7gCHo1LEFf0',
    appId: '1:120954544713:ios:aa75f6ad69e9bccab5d598',
    messagingSenderId: '120954544713',
    projectId: 'newpaysense-83ef4',
    storageBucket: 'newpaysense-83ef4.appspot.com',
    iosBundleId: 'com.example.paysense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXCLCW2cYqJY975bxP10PZ7gCHo1LEFf0',
    appId: '1:120954544713:ios:aa75f6ad69e9bccab5d598',
    messagingSenderId: '120954544713',
    projectId: 'newpaysense-83ef4',
    storageBucket: 'newpaysense-83ef4.appspot.com',
    iosBundleId: 'com.example.paysense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZXZfBvx3e6HQ4Ffi-RY1NUe3QpVNjx6A',
    appId: '1:120954544713:web:1229a7595ce8a91cb5d598',
    messagingSenderId: '120954544713',
    projectId: 'newpaysense-83ef4',
    authDomain: 'newpaysense-83ef4.firebaseapp.com',
    storageBucket: 'newpaysense-83ef4.appspot.com',
    measurementId: 'G-4ZLM3ZEDM1',
  );
}
